// =====================================================
// Email Service - Office 365 SMTP
// =====================================================
// 用途: 处理Contact Us表单的双邮件发送
// - 发送管理员通知到 han@rwadealmaker.com
// - 发送客户确认邮件
// 创建日期: 2025-10-28
// =====================================================

const nodemailer = require('nodemailer');
require('dotenv').config();

// Office 365 SMTP 配置 - 从环境变量读取
const transporter = nodemailer.createTransport({
  host: process.env.EMAIL_HOST,
  port: parseInt(process.env.EMAIL_PORT),
  secure: false, // STARTTLS
  auth: {
    user: process.env.EMAIL_USER,
    pass: process.env.EMAIL_PASSWORD
  },
  tls: {
    ciphers: 'SSLv3'
  }
});

/**
 * 发送管理员通知邮件
 * @param {Object} formData - 表单数据
 * @param {String} formData.name - 客户姓名
 * @param {String} formData.email - 客户邮箱
 * @param {String} formData.type - 客户类型 (individual/business/other)
 * @param {String} formData.subject - 咨询主题
 * @param {String} formData.message - 留言内容
 * @returns {Promise}
 */
async function sendAdminNotification(formData) {
  const typeMapping = {
    'individual': 'Individual Investor',
    'business': 'Business/Institution',
    'other': 'Other'
  };

  const subjectMapping = {
    'investor': 'Investor Enquiry',
    'asset_holder': 'Asset Holder Enquiry',
    'general': 'General Enquiry',
    'technical': 'Technical Support',
    'business': 'Business Cooperation',
    'other': 'Other'
  };

  const emailSubject = subjectMapping[formData.subject] || 'New Enquiry';
  const customerType = typeMapping[formData.type] || formData.type;

  const mailOptions = {
    from: 'han@rwadealmaker.com',
    to: 'han@rwadealmaker.com',
    subject: `🔔 New Enquiry: ${emailSubject}`,
    html: `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 10px 10px 0 0;
          }
          .content {
            background: #f9f9f9;
            padding: 30px;
            border: 1px solid #e0e0e0;
            border-radius: 0 0 10px 10px;
          }
          .field {
            margin-bottom: 20px;
          }
          .field-label {
            font-weight: bold;
            color: #667eea;
            margin-bottom: 5px;
          }
          .field-value {
            background: white;
            padding: 12px;
            border-radius: 5px;
            border-left: 3px solid #667eea;
          }
          .message-box {
            background: white;
            padding: 15px;
            border-radius: 5px;
            border-left: 3px solid #764ba2;
            min-height: 100px;
            white-space: pre-wrap;
          }
          .footer {
            text-align: center;
            margin-top: 30px;
            color: #888;
            font-size: 12px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 style="margin: 0;">New Contact Form Submission</h1>
          <p style="margin: 10px 0 0 0;">RWA Deal Maker Platform</p>
        </div>

        <div class="content">
          <div class="field">
            <div class="field-label">Customer Name</div>
            <div class="field-value">${formData.name}</div>
          </div>

          <div class="field">
            <div class="field-label">Email Address</div>
            <div class="field-value">${formData.email}</div>
          </div>

          <div class="field">
            <div class="field-label">Customer Type</div>
            <div class="field-value">${customerType}</div>
          </div>

          <div class="field">
            <div class="field-label">Enquiry Subject</div>
            <div class="field-value">${emailSubject}</div>
          </div>

          <div class="field">
            <div class="field-label">Message</div>
            <div class="message-box">${formData.message}</div>
          </div>
        </div>

        <div class="footer">
          <p>This email was automatically generated by RWA Deal Maker Contact Form</p>
          <p>Timestamp: ${new Date().toLocaleString('en-AU', { timeZone: 'Australia/Sydney' })} (AEST)</p>
        </div>
      </body>
      </html>
    `
  };

  return transporter.sendMail(mailOptions);
}

/**
 * 发送客户确认邮件
 * @param {String} customerEmail - 客户邮箱
 * @param {String} customerName - 客户姓名
 * @returns {Promise}
 */
async function sendCustomerConfirmation(customerEmail, customerName) {
  const mailOptions = {
    from: 'han@rwadealmaker.com',
    to: customerEmail,
    subject: '✅ Thank you for contacting RWA Deal Maker',
    html: `
      <!DOCTYPE html>
      <html>
      <head>
        <style>
          body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
          }
          .header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 30px;
            text-align: center;
            border-radius: 10px 10px 0 0;
          }
          .content {
            background: #f9f9f9;
            padding: 30px;
            border: 1px solid #e0e0e0;
            border-radius: 0 0 10px 10px;
          }
          .highlight-box {
            background: white;
            padding: 20px;
            border-radius: 8px;
            border-left: 4px solid #667eea;
            margin: 20px 0;
          }
          .footer {
            text-align: center;
            margin-top: 30px;
            color: #888;
            font-size: 12px;
            border-top: 1px solid #e0e0e0;
            padding-top: 20px;
          }
          .btn {
            display: inline-block;
            padding: 12px 30px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            text-decoration: none;
            border-radius: 5px;
            margin-top: 20px;
          }
        </style>
      </head>
      <body>
        <div class="header">
          <h1 style="margin: 0;">Thank You for Reaching Out</h1>
          <p style="margin: 10px 0 0 0;">RWA Deal Maker</p>
        </div>

        <div class="content">
          <p>Dear ${customerName},</p>

          <div class="highlight-box">
            <p style="margin: 0; font-size: 16px;">
              ✅ <strong>We have received your enquiry successfully!</strong>
            </p>
          </div>

          <p>
            Thank you for contacting RWA Deal Maker. Our team has been notified of your enquiry
            and will review your message promptly.
          </p>

          <p>
            <strong>What happens next?</strong>
          </p>
          <ul>
            <li>Our team will review your enquiry within 1-2 business days</li>
            <li>You will receive a personalized response to this email address</li>
            <li>For urgent matters, please call us directly</li>
          </ul>

          <p>
            In the meantime, feel free to explore our platform and discover the latest
            Real World Asset investment opportunities.
          </p>

          <div style="text-align: center;">
            <a href="http://localhost:5173/" class="btn">Visit Our Platform</a>
          </div>

          <div style="margin-top: 30px; padding: 20px; background: #fff3cd; border-radius: 5px;">
            <p style="margin: 0;"><strong>📧 Contact Information:</strong></p>
            <p style="margin: 5px 0;">Email: han@rwadealmaker.com</p>
            <p style="margin: 5px 0;">Website: www.rwadealmaker.com</p>
          </div>
        </div>

        <div class="footer">
          <p>This is an automated confirmation email. Please do not reply directly to this message.</p>
          <p>© ${new Date().getFullYear()} RWA Deal Maker. All rights reserved.</p>
        </div>
      </body>
      </html>
    `
  };

  return transporter.sendMail(mailOptions);
}

/**
 * 测试SMTP连接
 */
async function testConnection() {
  try {
    await transporter.verify();
    console.log('✅ SMTP连接成功 - Office 365');
    return true;
  } catch (error) {
    console.error('❌ SMTP连接失败:', error.message);
    return false;
  }
}

module.exports = {
  sendAdminNotification,
  sendCustomerConfirmation,
  testConnection
};
