-- =====================================================
-- 创建project_active和project_incoming表（不使用触发器）
-- project_code将在应用层生成
-- =====================================================

-- 1. 创建 project_active 表
CREATE TABLE IF NOT EXISTS `project_active` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '项目ID',
  `project_code` VARCHAR(20) NOT NULL UNIQUE COMMENT '项目代码 (RWAT001, RWAT002...)',
  `project_name` VARCHAR(255) NOT NULL COMMENT '项目名称',
  `property_summary` TEXT COMMENT '物业摘要',
  `status` ENUM('ACTIVE', 'COMPLETED', 'DEFAULT') NOT NULL DEFAULT 'ACTIVE' COMMENT '项目状态',
  `total_offering_token` DECIMAL(20, 2) DEFAULT 0 COMMENT '总发行代币数',
  `subscribe_token` DECIMAL(20, 2) DEFAULT 0 COMMENT '已认购代币数',
  `token_price` DECIMAL(20, 2) DEFAULT 1 COMMENT '代币单价',
  `loan_amount` DECIMAL(20, 2) COMMENT '贷款金额',
  `interest_rate` DECIMAL(5, 2) COMMENT '年利率 (%)',
  `loan_term_months` INT COMMENT '贷款期限 (月)',
  `lvr` DECIMAL(5, 2) COMMENT '贷款价值比 (LVR %)',
  `property_location` VARCHAR(255) COMMENT '物业地址',
  `property_state` VARCHAR(50) COMMENT '物业州/省',
  `property_type` VARCHAR(50) COMMENT '物业类型 (Residential/Commercial/Industrial/Land)',
  `property_value` DECIMAL(20, 2) COMMENT '物业估值',
  `loan_type` VARCHAR(50) COMMENT '贷款类型 (First/Second)',
  `loan_product` VARCHAR(100) COMMENT '贷款产品',
  `loan_purpose` VARCHAR(100) COMMENT '贷款用途 (Purchase/Refinance/Construction)',
  `mortgage_type` VARCHAR(50) COMMENT '抵押类型 (First_Mortgage/Second_Mortgage)',
  `borrower` VARCHAR(100) COMMENT '借款人类型 (Individual/Company/Trust)',
  `lender` VARCHAR(255) COMMENT '贷款方',
  `issuer` VARCHAR(255) COMMENT '发行方',
  `guarantor` VARCHAR(255) COMMENT '担保方',
  `collateral` VARCHAR(100) COMMENT '抵押物类型 (Residential_Property/Commercial_Property/Land)',
  `security_rank` VARCHAR(50) COMMENT '抵押顺位 (First/Second)',
  `commencement_date` DATE COMMENT '开始日期',
  `expiry_date` DATE COMMENT '到期日期',
  `drawdown_date` DATE COMMENT '放款日期',
  `expected_recovery_date` DATE COMMENT '预期回收日期',
  `repayment_arrangement` VARCHAR(100) COMMENT '还款安排 (Interest_Only/Principal_And_Interest)',
  `early_repayment` VARCHAR(20) COMMENT '提前还款 (Allowed/Not_Allowed)',
  `early_repayment_details` TEXT COMMENT '提前还款详情',
  `default_interest_rate` DECIMAL(5, 2) COMMENT '违约利率 (%)',
  `default_triggers` TEXT COMMENT '违约触发条件',
  `default_process` TEXT COMMENT '违约处理流程',
  `valuation_report` VARCHAR(500) COMMENT '估值报告URL',
  `mortgage_deed` VARCHAR(500) COMMENT '抵押文件URL',
  `issuer_token` VARCHAR(500) COMMENT '发行方代币文档URL',
  `loan_token` VARCHAR(500) COMMENT '贷款代币文档URL',
  `principal_token_address` VARCHAR(42) COMMENT '本金代币合约地址 (LPRI)',
  `interest_token_address` VARCHAR(42) COMMENT '利息代币合约地址 (LINT)',
  `loan_issuer_address` VARCHAR(42) COMMENT 'LoanIssuer合约地址',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` VARCHAR(100) COMMENT '创建人',
  `updated_by` VARCHAR(100) COMMENT '更新人',
  INDEX `idx_project_code` (`project_code`),
  INDEX `idx_status` (`status`),
  INDEX `idx_property_type` (`property_type`),
  INDEX `idx_loan_type` (`loan_type`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='已代币化RWA项目表';

-- 2. 创建 project_incoming 表
CREATE TABLE IF NOT EXISTS `project_incoming` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '项目ID',
  `project_code` VARCHAR(20) NOT NULL UNIQUE COMMENT '项目代码 (RWA001, RWA002...)',
  `project_name` VARCHAR(255) NOT NULL COMMENT '项目名称',
  `property_summary` TEXT COMMENT '物业摘要',
  `status` ENUM('INCOMING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'INCOMING' COMMENT '项目状态',
  `estimated_total_token` DECIMAL(20, 2) DEFAULT 0 COMMENT '预计发行代币数',
  `estimated_token_price` DECIMAL(20, 2) DEFAULT 1 COMMENT '预计代币单价',
  `loan_amount` DECIMAL(20, 2) COMMENT '贷款金额',
  `interest_rate` DECIMAL(5, 2) COMMENT '年利率 (%)',
  `loan_term_months` INT COMMENT '贷款期限 (月)',
  `lvr` DECIMAL(5, 2) COMMENT '贷款价值比 (LVR %)',
  `property_location` VARCHAR(255) COMMENT '物业地址',
  `property_state` VARCHAR(50) COMMENT '物业州/省',
  `property_type` VARCHAR(50) COMMENT '物业类型 (Residential/Commercial/Industrial/Land)',
  `property_value` DECIMAL(20, 2) COMMENT '物业估值',
  `loan_type` VARCHAR(50) COMMENT '贷款类型 (First/Second)',
  `loan_product` VARCHAR(100) COMMENT '贷款产品',
  `loan_purpose` VARCHAR(100) COMMENT '贷款用途 (Purchase/Refinance/Construction)',
  `mortgage_type` VARCHAR(50) COMMENT '抵押类型 (First_Mortgage/Second_Mortgage)',
  `borrower` VARCHAR(100) COMMENT '借款人类型 (Individual/Company/Trust)',
  `lender` VARCHAR(255) COMMENT '贷款方',
  `issuer` VARCHAR(255) COMMENT '发行方',
  `guarantor` VARCHAR(255) COMMENT '担保方',
  `collateral` VARCHAR(100) COMMENT '抵押物类型 (Residential_Property/Commercial_Property/Land)',
  `security_rank` VARCHAR(50) COMMENT '抵押顺位 (First/Second)',
  `expected_commencement_date` DATE COMMENT '预计开始日期',
  `expected_expiry_date` DATE COMMENT '预计到期日期',
  `expected_drawdown_date` DATE COMMENT '预计放款日期',
  `repayment_arrangement` VARCHAR(100) COMMENT '还款安排 (Interest_Only/Principal_And_Interest)',
  `early_repayment` VARCHAR(20) COMMENT '提前还款 (Allowed/Not_Allowed)',
  `early_repayment_details` TEXT COMMENT '提前还款详情',
  `default_interest_rate` DECIMAL(5, 2) COMMENT '违约利率 (%)',
  `default_triggers` TEXT COMMENT '违约触发条件',
  `default_process` TEXT COMMENT '违约处理流程',
  `valuation_report` VARCHAR(500) COMMENT '估值报告URL',
  `mortgage_deed` VARCHAR(500) COMMENT '抵押文件URL',
  `review_notes` TEXT COMMENT '审核备注',
  `approved_by` VARCHAR(100) COMMENT '审批人',
  `approved_at` TIMESTAMP NULL COMMENT '审批时间',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `created_by` VARCHAR(100) COMMENT '创建人',
  `updated_by` VARCHAR(100) COMMENT '更新人',
  INDEX `idx_project_code` (`project_code`),
  INDEX `idx_status` (`status`),
  INDEX `idx_property_type` (`property_type`),
  INDEX `idx_loan_type` (`loan_type`),
  INDEX `idx_created_at` (`created_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='待代币化RWA项目表';

-- 3. 创建统一视图
CREATE OR REPLACE VIEW `v_all_projects` AS
SELECT
  project_code,
  project_name,
  property_summary,
  status,
  'ACTIVE' as project_category,
  loan_amount,
  interest_rate,
  loan_term_months,
  property_location,
  property_type,
  created_at
FROM project_active
UNION ALL
SELECT
  project_code,
  project_name,
  property_summary,
  status,
  'INCOMING' as project_category,
  loan_amount,
  interest_rate,
  loan_term_months,
  property_location,
  property_type,
  created_at
FROM project_incoming;
