import { ref, computed } from 'vue'

// 语言状态管理
const currentLanguage = ref('zh')

// 语言配置
const languages = {
  zh: {
    name: '中文',
    code: 'zh',
    dir: 'ltr'
  },
  en: {
    name: 'English',
    code: 'en',
    dir: 'ltr'
  }
}

// 语言包
const translations = {
  zh: {
    // 通用
    'common.home': '首页',
    'common.products': '产品',
    'common.about': '关于我们',
    'common.contact': '联系我们',
    'common.settings': '设置',
    'common.profile': '个人中心',
    'common.login': '登录',
    'common.signup': '注册',
    'common.logout': '退出登录',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.loading': '加载中...',
    'common.loadingVideo': '加载视频...',
    'common.loadingProducts': '加载产品数据...',
    'common.videoLoadError': '视频加载失败',
    'common.loadFailed': '加载失败',
    'common.retry': '重试',
    'common.refresh': '刷新',
    'common.close': '关闭',
    'common.sending': '发送中...',
    'common.error': '错误',
    'common.success': '成功',
    'common.browserNotSupported': '你的浏览器不支持视频播放',
    'common.skipVideo': '跳过视频',
    
    // 导航
    'nav.home': '首页',
    'nav.listedProjects': '已上链RWA',
    'nav.toBeListed': '待上链RWA',
    'nav.trading': '交易',
    'nav.about': '关于我们',
    'nav.contact': '联系我们',
    'nav.more': '更多',
    'nav.portfolio': '我的投资组合',
    'nav.settings': '设置',
    'nav.profile': '个人中心',
    'nav.notifications': '通知',
    
    // 钱包相关
    'wallet.connect': '连接钱包',
    'wallet.connect.description': '选择一个MetaMask账户来连接到您的个人资料:',
    'wallet.connect.new': '连接新钱包',
    'wallet.connected': '已连接',
    'wallet.disconnect': '断开钱包',
    'wallet.disconnect.confirm': '您确定要断开这个钱包吗？',
    'wallet.disconnect.select': '选择要断开的钱包账户：',
    'wallet.disconnected': '钱包已断开',
    'wallet.management': '钱包管理',
    'wallet.networkSwitchNote': '当您在钱包中切换网络时，本页网络会自动切换',
    'wallet.address': '钱包地址',
    'wallet.balance': '余额',
    'wallet.transaction': '交易',
    'wallet.noAccounts': '没有找到MetaMask中的其他账户。',
    'wallet.addAccounts': '请在MetaMask中添加更多账户并重试。',
    'wallet.account': '账户',
    'wallet.copy': '复制',
    'wallet.copied': '已复制',
    'wallet.connectWalletManagement': '请在钱包管理中连接您的钱包',
    'wallet.currentNetwork': '当前网络',
    'wallet.portfolio': '投资组合',
    'wallet.insertContractAddress': '或在此插入您的合约地址：',
    'wallet.pasteERC20Address': '粘贴ERC20合约地址',
    'wallet.labelOptional': '标签（可选）',
    'wallet.addToken': '添加代币',
    'wallet.refresh': '刷新',
    'wallet.refreshTokens': '刷新代币列表',
    'wallet.tokens': '代币',
    'wallet.clickForDetails': '点击可查看详情',
    
    // Token Detail
    'tokenDetail.title': '代币详情',
    'tokenDetail.overview': '概览',
    'tokenDetail.networkName': '网络名称',
    'tokenDetail.contractAddress': '合约地址',
    'tokenDetail.tokenDecimal': '代币精度',
    'tokenDetail.spendingCaps': '消费限制',
    'tokenDetail.tokenImportDate': '代币导入日期',
    'tokenDetail.tokenImportSource': '代币导入来源',
    'tokenDetail.viewAssetInExplorer': '在浏览器中查看资产',
    'tokenDetail.hide': '隐藏',
    'tokenDetail.deleteFromWallet': '从我的钱包中删除',
    'tokenDetail.hiddenSuccessfully': '隐藏成功',
    'tokenDetail.hideFailed': '隐藏失败',
    'tokenDetail.deletedFromCustomTokens': '已从自定义代币中删除',
    'tokenDetail.deleteFailed': '删除失败',
    'wallet.connectSelectedAccount': '连接选定的账户',
    'wallet.loadingAccounts': '加载账户...',
    'wallet.account': '账户',
    'wallet.disconnectSuccess': '钱包已断开',
    'wallet.disconnectSuccessMsg': '钱包已成功断开连接',
    'wallet.addressAdded': '钱包地址 {address} 已添加',
    'wallet.addressExists': '该钱包地址已存在',
    'wallet.invalidAddress': '请输入有效的以太坊地址',
    'wallet.noWalletToSet': '没有可设置的钱包地址',
    'wallet.primaryWalletSet': '主钱包已设置为: {wallet}',
    'wallet.invalidSelection': '无效的选择',
    'wallet.walletDisconnected': '钱包 {address} 已断开连接',
    
    // 设置页面
    'settings.title': '设置',
    'settings.subtitle': '管理您的应用程序设置',
    'settings.general': '常规',
    'settings.general.description': '基本应用程序设置和偏好',
    'settings.theme': '主题',
    'settings.theme.description': '选择您偏好的主题',
    'settings.language': '语言',
    'settings.language.description': '选择您偏好的语言',
    'settings.theme.dark': '深色',
    'settings.theme.light': '浅色',
    'settings.language.zh': '中文',
    'settings.language.en': '英语',
    'settings.timezone': '时区',
    'settings.timezone.description': '设置您的本地时区',
    'settings.timezone.utc': 'UTC',
    'settings.timezone.est': '东部时间',
    'settings.timezone.pst': '太平洋时间',
    'settings.timezone.cst': '中国标准时间',
    'settings.notifications': '通知',
    'settings.notifications.description': '通知偏好和提醒设置',
    'settings.privacy': '隐私',
    'settings.privacy.description': '隐私控制和数据设置',
    'settings.security': '安全',
    'settings.security.description': '密码、身份验证和安全设置',
    'settings.wallet': '钱包',
    'settings.wallet.description': '钱包连接和交易设置',
    'settings.performance': '性能',
    'settings.performance.description': '性能优化和缓存设置',
    'settings.account': '账户',
    'settings.account.description': '账户选项和个人资料设置',
    'settings.trading': '交易',
    'settings.trading.description': '交易偏好和选项设置',
    'settings.advanced': '高级',
    'settings.advanced.description': '高级设置和开发者选项',
    
    // 开场视频
    'settings.introVideo': '开场视频',
    'settings.introVideo.description': '重新观看网站开场视频',
    'settings.introVideo.watch': '观看开场视频',
    
    // 安全设置
    'settings.password': '密码',
    'settings.password.description': '更改您的账户密码',
    'settings.password.change': '更改密码',
    'settings.sessionTimeout': '会话超时',
    'settings.sessionTimeout.description': '设置自动登出时间',
    'settings.sessionTimeout.15min': '15分钟',
    'settings.sessionTimeout.30min': '30分钟',
    'settings.sessionTimeout.1hour': '1小时',
    'settings.sessionTimeout.8hours': '8小时',
    'settings.loginAlerts': '登录提醒',
    'settings.loginAlerts.description': '接收新登录尝试的通知',
    
    // 钱包设置
    'settings.defaultWallet': '默认钱包',
    'settings.defaultWallet.description': '选择您偏好的钱包提供商',
    'settings.defaultWallet.metamask': 'MetaMask',
    'settings.defaultWallet.walletconnect': '钱包连接器',
    'settings.autoConnect': '自动连接',
    'settings.autoConnect.description': '在页面加载时自动连接钱包',
    'settings.gasSettings': 'Gas设置',
    'settings.gasSettings.description': '配置交易Gas偏好',
    'settings.gasSettings.configure': 'Gas设置',
    'settings.connectWallet': '连接钱包',
    'settings.connectWallet.description': '连接或断开您的钱包',
    'settings.connectWallet.button': '连接钱包',
    'settings.walletAddress': '钱包地址',
    'settings.walletAddress.description': '查看您的钱包地址',
    'settings.walletAddress.view': '查看地址',
    
    // 通知设置
    'settings.pushNotifications': '推送通知',
    'settings.pushNotifications.description': '启用浏览器推送通知',
    'settings.emailNotifications': '邮箱通知',
    'settings.emailNotifications.description': '通过邮箱接收重要更新',
    'settings.smsNotifications': 'SMS通知',
    'settings.smsNotifications.description': '通过短信接收重要更新',
    
    // 性能设置
    'settings.autoRefresh': '自动刷新',
    'settings.autoRefresh.description': '自动刷新数据',
    'settings.autoRefresh.disabled': '禁用',
    'settings.autoRefresh.30sec': '30秒',
    'settings.autoRefresh.1min': '1分钟',
    'settings.autoRefresh.5min': '5分钟',
    'settings.cacheSize': '缓存大小',
    'settings.cacheSize.description': '最大缓存存储大小',
    'settings.clearCache': '清除缓存',
    'settings.clearCache.description': '清除所有缓存数据',
    'settings.clearCache.button': '清除缓存',
    
    // 账户设置
    'settings.profileVisibility': '主页可见性',
    'settings.profileVisibility.description': '控制谁可以看到您的个人信息',
    'settings.profileVisibility.public': '公开',
    'settings.profileVisibility.friends': '仅好友可见',
    'settings.profileVisibility.private': '私密',
    'settings.twoFactorAuth': '两步验证',
    'settings.twoFactorAuth.description': '为您的账户添加额外一层安全性',
    'settings.twoFactorAuth.enable': '启用两步验证',
    
    // 交易设置
    'settings.defaultTradingPair': '默认交易对',
    'settings.defaultTradingPair.description': '设置您偏好的交易对以快速访问',
    'settings.defaultTradingPair.ethUsdt': 'ETH/USDT(以太坊/美元)',
    'settings.defaultTradingPair.btcUsdt': 'BTC/USDT(比特币/美元)',
    'settings.defaultTradingPair.usdcUsdt': 'USDC/USDT(美元稳定币/美元)',
    'settings.autoConfirmTrades': '自动确认交易',
    'settings.autoConfirmTrades.description': '在指定金额下自动确认交易',
    'settings.priceAlerts': '价格提醒',
    'settings.priceAlerts.description': '当价格达到您设定的目标时通知您',
    'settings.priceAlerts.manage': '管理提醒',
    
    // 隐私设置
    'settings.dataCollection': '数据收集',
    'settings.dataCollection.description': '允许我们收集匿名使用数据',
    'settings.marketingEmails': '营销邮箱',
    'settings.marketingEmails.description': '接收促销邮件和更新',
    'settings.thirdPartySharing': '第三方分享',
    'settings.thirdPartySharing.description': '允许与信任的合作伙伴共享数据',
    
    // 高级设置
    'settings.apiAccess': 'API访问',
    'settings.apiAccess.description': '管理您的API密钥和权限',
    'settings.apiAccess.configure': 'API设置',
    'settings.exportData': '导出数据',
    'settings.exportData.description': '下载您的账户数据',
    'settings.exportData.button': '导出',
    'settings.analytics': '分析',
    'settings.analytics.description': '帮助改进应用程序通过共享使用数据',
    'settings.resetPreferences': '重置偏好',
    'settings.resetPreferences.description': '重置所有选项为默认值',
    'settings.resetPreferences.button': '重置所有',
    
    // 项目相关
    'project.title': '项目',
    'project.name': '项目名称',
    'project.code': '项目代码',
    'project.status': '状态',
    'project.yield': '收益率',
    'project.term': '期限',
    'project.amount': '金额',
    'project.progress': '进度',
    'project.details': '详情',
    'project.invest': '投资',
    'project.trade': '交易',
    'project.loanAmount': '贷款金额',
    'project.interestRate': '预期收益率',
    'project.perYear': '/年',
    'project.loanTerm': '贷款期限',
    'project.months': '月',
    'project.currentSubscription': '当前认购',
    'project.totalOffering': '代币发行量',
    'project.subscribed': '已认购',
    'project.partyInfo': '相关方信息',
    'project.issuer': '发行主体',
    'project.underlyingAsset': '底层资产',
    'project.sponsor': '保荐人',
    'project.valuer': '评估机构',
    'project.lawyer': '律师',
    'project.trustee': '监管方',
    'project.viewOnEtherscan': '在Etherscan上查看',
    
    // 个人中心
    'profile.title': '个人中心',
    'profile.info': '个人信息',
    'profile.email': '邮箱',
    'profile.phone': '手机号',
    'profile.wallet': '钱包',
    'profile.kyc': 'KYC认证',
    'profile.whitelist': '白名单',
    'profile.trading': '交易权限',
    
    // 关于我们
    'about.title': '关于我们',
    'about.headline': '我们是专注于把房地产资产包装成投资人喜欢的RWA底层资产的RWA Dealmaker',
    'about.description': '我们致力于为投资者提供透明、安全、高效的房地产代币化投资平台。',
    'about.intro1': '我们是专注于把房地产资产包装成投资人喜欢的RWA底层资产的RWA Dealmaker，即平台以保护RWA投资人的资金安全为核心，精选合法合规，风险低，回报高的优质资产（如澳大利亚抵押率不超过70%，利率大约为9%的第一抵押权人的住宅抵押贷款资产），促成投资人和资产持有人交易的dealmaker。',
    'about.intro2': '平台上展示的底层资产受资产所在国家的法律保护，且资金可以自由进出该国家。如果投资人有要求，项目交易结构可以让底层资产和资金独立隔离和托管给合格的第三方机构。',
    'about.intro3': '除了促成投资人和RWA底层资产持有人达成交易以外，本平台还整合RWA代币化全链条的生态合作，涵盖专业RWA代币化的技术服务公司，持牌RWA代币发行商和交易所等，确保RWA代币化合法的，高效的，低成本的公开或非公开发行的成功。',
    
    // 联系我们
    'contact.title': '联系我们',
    'contact.description': '如果您想将房地产资产或房地产抵押贷款资产作为RWA的底层资产进行融资或有意购买RWA资产，欢迎联系我们。',
    'contact.name': '姓名',
    'contact.name.placeholder': '请输入您的全名',
    'contact.email': '邮箱',
    'contact.email.placeholder': '请输入您的邮箱',
    'contact.type': '类型',
    'contact.type.placeholder': '请选择',
    'contact.type.individual': '个人',
    'contact.type.business': '企业',
    'contact.type.other': '其他',
    'contact.subject': '主题',
    'contact.subject.placeholder': '请选择',
    'contact.subject.investor': '投资咨询',
    'contact.subject.asset_holder': '资产列表',
    'contact.subject.general': '一般问题',
    'contact.subject.technical': '技术支持',
    'contact.subject.business': '业务合作',
    'contact.subject.other': '其他',
    'contact.message': '消息',
    'contact.message.placeholder': '告诉我们您想投资什么项目...',
    'contact.send': '发送消息',
    'follow.us': '关注我们',
    
    // 页脚
    'footer.disclaimer': '免责声明：本平台提供的信息仅供参考，不保证其真实性、准确性或完整性，亦不构成投资邀约或投资建议。',
    'footer.copyright': '© 2025 RWA Dealmaker. All rights reserved.',
    
    // 交易页面 - 项目信息
    'trade.projectInfo': '项目信息',
    'trade.issuer': '发行主体',
    'trade.estimateReturn': '预期收益',
    'trade.tokenizedAmount': '代币发行量',
    'trade.underlyingAsset': '底层资产',
    'trade.valuer': '评估机构',
    'trade.lawyer': '律师',
    'trade.trustee': '监管方',
    'trade.year': '年',
    
    // 底层资产 - 贷款信息
    'trade.underlyingAssetLoanInfo': '底层资产 - 贷款信息',
    'trade.lender': '贷款人',
    'trade.borrower': '借款人',
    'trade.loanAmount': '借款金额',
    'trade.collateral': '抵押物',
    'trade.valuation': '评估值',
    'trade.lvr': '抵押率',
    'trade.mortgageTitle': '抵押权',
    'trade.firstMortgage': '第一抵押权人',
    'trade.interestRate': '利率',
    'trade.loanTerm': '借款期限',
    'trade.months': '个月',
    'trade.defaultInterestRate': '违约利息',
    
    // 抵押物信息
    'trade.collateralInfo': '抵押物信息',
    'trade.assetAddress': '资产地址',
    'trade.siteArea': '占地面积',
    'trade.floorArea': '建筑面积',
    'trade.propertyType': '房产类型',
    'trade.squareMeters': '平方米',
    
    // 代币信息
    'trade.tokenInfo': '代币信息 - 发行与认购信息',
    'trade.underlyingAssetSize': '底层资产规模',
    'trade.totalTokenizedAmount': '总发行量',
    'trade.subscribedAmount': '已认购量',
    'trade.subscriptionPercentage': '认购比例',
    
    // 交易页面 - 合约地址
    'trade.contractAddress': '合约地址',
    'trade.contractAddressDescription': '以下合约地址将用于此次交易:',
    'trade.principalTokenAddress': '本金代币地址',
    'trade.interestTokenAddress': '利息代币地址',
    'trade.kycRegistryAddress': 'KYC注册地址',
    'trade.loanIssuerAddress': '贷款发行方地址',
    'trade.continueTransaction': '继续交易',
    'trade.transactionSuccess': '交易成功!',
    'trade.transactionCompleted': '您的交易已经完成!',
    'trade.transactionDetails': '交易详情',
    'trade.type': '类型',
    'trade.buy': '买入',
    'trade.sell': '卖出',
    'trade.amount': '数量',
    'trade.blockchainInfo': '区块链咨询',
    'trade.hash': '哈希值',
    'trade.block': '区块',
    'trade.contractAddresses': '合约地址',
    'trade.principalToken': '本金代币',
    'trade.interestToken': '利息代币',
    'trade.loadingProjectData': '加载产品数据...',
    'trade.pleaseWait': '请稍候，我们正在加载项目信息',
    'trade.loadingFailed': '加载失败',
    'trade.retry': '重试',
    'trade.subscriptionInfo': '认购信息',
    'trade.totalOffering': '总发行量',
    'trade.subscribed': '已认购量',
    'trade.subscriptionRatio': '认购比例',
    'trade.loanInfo': '贷款信息',
    'trade.loanAmount': '贷款金额',
    'trade.expectedYield': '预计收益率',
    'trade.term': '期限',
    'trade.ltvRatio': '抵押率',
    'trade.defaultRate': '违约利率',
    'trade.lender': '贷款方',
    'trade.borrower': '借款方',
    'trade.collateralInfo': '抵押物信息',
    'trade.appraisalValue': '评估值',
    'trade.address': '地址',
    'trade.mortgageType': '抵押类型',
    'trade.sponsor': '保荐人',
    'trade.appraiser': '评估机构',
    'trade.lawyer': '律师',
    'trade.trustee': '监管方',
    'trade.smartContractAddresses': '智能合约地址',
    'trade.interestTokenAddressLabel': '利息代币地址',
    'trade.subscribe': '跳转认购',
    'trade.walletAddress': '钱包地址',
    'trade.quantityTokens': '数量（代币）',
    'trade.enterQuantity': '输入数量',
    'trade.projectUpdates': '项目更新',
    'trade.newsItem1': '项目正式启动，开始接受投资申请',
    'trade.newsItem2': '完成项目尽职调查，风险评估报告已发布',
    'trade.newsItem3': '项目抵押物评估完成，估值确认',
    'trade.newsItem4': '项目上线，详细信息已更新',
    
    // 认购摘要
    'trade.subscriptionSummary': '认购摘要',
    'trade.redemptionSummary': '赎回摘要',
    'trade.projectCode': '项目代码',
    'trade.projectName': '项目名称',
    'trade.tradeType': '交易类型',
    'trade.tokenPurchase': '代币认购',
    'trade.interestRedemption': '利息赎回',
    'trade.tokenAmount': '代币数量',
    'trade.tokens': '代币',
    'trade.annualYield': '年化收益率',
    'trade.expectedReturn': '预期收益',
    'trade.loanTerm': '贷款期限',
    'trade.riskWarning': '投资需自担风险。请仔细阅读项目详情,并评估自身的风险承受能力。',
    
    // 认购状态弹窗
    'trade.submitting': '正在提交认购...',
    'trade.submittingDesc': '请稍候，我们正在处理您的认购申请',
    'trade.submitted': '认购已提交!',
    'trade.submittedDesc': '您的认购申请已成功提交，请等待审核',
    'trade.failed': '认购提交失败',
    'trade.viewPortfolio': '查看投资组合',
    'trade.resubmit': '重新提交',
    'trade.confirmSubscription': '确认认购',
    'trade.confirmRedemption': '确认赎回',
    'trade.subscriptionSubmitted': '您的认购申请已提交',
    'trade.checkEmailForUpdates': '请检查邮箱内连接，追踪申请动态',
    'trade.processing': '处理中...',
    'trade.processingTitle': '处理中...',
    'trade.processingDesc': '我们正在处理您的交易请求，请稍候...',
    
    // Profile页面
    'profile.personalCenter': '个人中心',
    'profile.personalInfo': '个人信息',
    'profile.email': '邮箱:',
    'profile.phone': '手机号:',
    'profile.password': '密码:',
    'profile.verifyEmail': '验证邮箱',
    'profile.verifyPhone': '验证手机号',
    'profile.addPhone': '添加手机号',
    'profile.changePhone': '修改手机号',
    'profile.changePassword': '修改密码',
    'profile.status': '状态:',
    'profile.loadingUserInfo': '加载用户信息...',
    'profile.notProvided': '未提供',
    'profile.accountStatus': '账户状态',
    'profile.kycVerification': 'KYC 验证',
    'profile.startVerification': '立即验证',
    'profile.tradingPermission': '交易权限',
    'profile.start': '开始',
    'profile.cancelVerification': '取消验证',
    'profile.logout': '安全退出',
    'profile.checkEmail': '检查您的邮箱',
    'profile.verifyEmailDescription': '我们发送了一封带有验证按钮的邮件到您的邮箱。<br>您收到了邮件吗？如果没有，请检查您的垃圾邮件文件夹或请求新的验证邮件，有效期为3天。<br>如果您在3天内未验证您的邮箱地址，您将需要创建一个新账户。<br>如果您遇到问题，请参阅账户帮助。',
    'profile.accountHelp': '账户帮助',
    'profile.subscribe': '订阅',
    'profile.unsubscribe': '取消订阅',
    'profile.privacy': '隐私 / 不卖我的信息',
    'profile.cookiePreferences': 'Cookie 偏好',
    'profile.confirm': '确定',
    
    // 登录页面
    'login.title': '登录您的账户',
    'login.subtitle': '欢迎来到RWADealmaker',
    'login.email': '邮箱',
    'login.emailPlaceholder': '输入您的邮箱',
    'login.password': '密码',
    'login.passwordPlaceholder': '输入您的密码',
    'login.remember': '记住30天',
    'login.forgotPassword': '忘记密码',
    'login.loginButton': '登录',
    'login.loggingIn': '登录中...',
    'login.noAccount': '没有账户？',
    'login.signupLink': '注册',
    
    // 注册页面
    'signup.title': '注册您的账户',
    'signup.subtitle': '欢迎来到RWADealmaker',
    'signup.email': '邮箱',
    'signup.emailPlaceholder': '输入您的邮箱',
    'signup.password': '密码',
    'signup.passwordPlaceholder': '输入您的密码',
    'signup.confirmPassword': '确认密码',
    'signup.confirmPasswordPlaceholder': '确认您的密码',
    'signup.passwordMatch': '✓ 密码匹配',
    'signup.passwordMismatch': '✗ 密码不匹配',
    'signup.name': '姓名',
    'signup.namePlaceholder': '输入您的姓名',
    'signup.phone': '电话号码',
    'signup.phonePlaceholder': '输入您的电话号码',
    'signup.agreeTerms': '我同意',
    'signup.terms': 'Terms',
    'signup.and': 'and',
    'signup.privacyPolicy': 'Privacy Policy.',
    'signup.agreeEmailUpdates': '我想要接收来自RWA的电子邮件更新。',
    'signup.signupButton': '注册',
    'signup.signingUp': '注册中...',
    'signup.haveAccount': '已经有账户？',
    'signup.loginLink': '登录',
    
    // KYC验证页面
    'kyc.back': '返回',
    'kyc.title': 'KYC 验证',
    'kyc.cancelVerification': '取消验证',
    'kyc.step1': '1. 上传证件并自动识别',
    'kyc.step2': '2. 活体检测',
    'kyc.step3': '3. 完成',
    'kyc.uploadIdTitle': '上传您的证件并自动读取信息',
    'kyc.uploadFront': '上传正面图片*',
    'kyc.uploadBack': '上传背面图片',
    'kyc.issuingCountry': '签发国家*',
    'kyc.selectCountry': '选择...',
    'kyc.idType': '证件类型*',
    'kyc.selectIdType': '选择...',
    'kyc.passport': '护照',
    'kyc.driverLicense': '驾驶执照',
    'kyc.idCard': '身份证',
    'kyc.residencePermit': '居住证',
    'kyc.autoRead': '从证件自动读取',
    'kyc.autoReadHint': '将使用 OCR/解析服务读取 first name, last name, DOB 等信息。',
    'kyc.firstName': '名*',
    'kyc.lastName': '姓*',
    'kyc.dateOfBirth': '出生日期*',
    'kyc.idNumber': '证件号码',
    'kyc.cancel': '取消',
    'kyc.continue': '继续',
    'kyc.livenessTitle': '活体检测',
    'kyc.livenessDescription': '将您的脸部置于框架中心并遵循指示。',
    'kyc.enableCamera': '启用摄像头',
    'kyc.livenessHint': '接入 Sumsub/Persona/Onfido 时，把此区域替换为他们的组件，并在成功回调里调用 complete()。',
    'kyc.back': '返回',
    'kyc.cancelLiveness': '取消',
    'kyc.verifiedTitle': '您的个人资料已验证',
    'kyc.verifiedDescription': '请等待白名单申请...',
    'kyc.backToProfile': '返回个人中心',
    'kyc.congratulations': '恭喜！',
    'kyc.kycCompleted': '您的KYC验证已成功完成。',
    'kyc.eligibleForWhitelist': '现在您有资格申请白名单并开始交易！',
    'kyc.maybeLater': '稍后再说',
    'kyc.applyForWhitelist': '申请白名单',
    'kyc.applyingWhitelist': '正在申请白名单...',
    'kyc.applyingWhitelistDescription': '请稍候，我们正在处理您的白名单申请。',
    'kyc.welcomeToWhitelist': '欢迎加入白名单！',
    'kyc.whitelistSuccess': '您已成功加入白名单。',
    'kyc.canSubscribe': '现在您可以前往产品页面订阅您喜欢的资产！',
    'kyc.goToProjects': '前往产品页面',
    'kyc.cancelKycTitle': '取消KYC验证',
    'kyc.cancelKycWarning': '取消KYC将撤销您的订阅资格。',
    'kyc.cancelKycConfirm': '您确定要取消KYC验证吗？',
    'kyc.continueKyc': '继续KYC',
    'kyc.yesCancelKyc': '是的，取消KYC',
    
    // 白名单申请
    'whitelist.status': '白名单状态',
    'whitelist.approved': '白名单已批准',
    'whitelist.pending': '白名单申请待审核',
    'whitelist.rejected': '不符合交易资格',
    'whitelist.apply': '申请白名单',
    'whitelist.applyNow': '立即申请',
    'whitelist.checkStatus': '查看状态',
    'whitelist.startTrading': '开始交易',
    'whitelist.reapply': '重新申请',
    'whitelist.applicationTitle': '申请白名单',
    'whitelist.applicationDescription': '您即将申请白名单以开始交易资产。',
    'whitelist.requirements': '要求：',
    'whitelist.kycCompleted': 'KYC验证已完成 ✅',
    'whitelist.validWallet': '有效的钱包连接',
    'whitelist.agreeTerms': '同意条款和条件',
    'whitelist.applying': '申请中...',
    'whitelist.close': '关闭',
    'whitelist.confirm': '确认',
    
    // 通知页面
    'notifications.title': '通知中心',
    'notifications.all': '全部',
    'notifications.unread': '未读',
    'notifications.read': '已读',
    'notifications.markAllRead': '全部标为已读',
    'notifications.markAsRead': '标为已读',
    'notifications.refresh': '刷新',
    'notifications.loading': '加载中...',
    'notifications.noNotifications': '暂无通知',
    'notifications.noNotificationsDesc': '您还没有收到任何通知',
    'notifications.viewDetails': '查看详情',
    'notifications.delete': '删除',
    'notifications.previous': '上一页',
    'notifications.next': '下一页',
    'notifications.page': '第',
    'notifications.justNow': '刚刚',
    'notifications.minutesAgo': '{count}分钟前',
    'notifications.hoursAgo': '{count}小时前',
    'notifications.daysAgo': '{count}天前',
    
    // 通知类型
    'notifications.types.transactionSuccess': '交易成功完成',
    'notifications.types.newProjectLaunched': '新项目上线',
    'notifications.types.subscriptionProgress': '认购进度更新',
    'notifications.types.kycStatusUpdate': 'KYC状态更新',
    'notifications.types.whitelistStatusUpdate': '白名单状态更新',
    'notifications.types.principalTokenReceived': '收到本金token',
    'notifications.types.interestTokenReceived': '收到利息token',
    'notifications.types.projectMaturity': '项目到期提醒',
    'notifications.types.subscriptionApplied': '认购申请已提交',
    'notifications.types.subscriptionUnderReview': '认购申请审批中',
    'notifications.types.subscriptionApproved': '认购申请已通过',
    
    // 通知操作按钮
    'notifications.actions.viewPortfolio': '查看投资组合',
    'notifications.actions.viewProject': '查看项目',
    'notifications.actions.viewProfile': '查看资料',
    'notifications.actions.viewDetails': '查看详情',
    'notifications.actions.payNow': '立即支付',
    'notifications.clearAll': '一键删除所有通知',
    'notifications.clearAllConfirm': '确定要删除所有通知吗？此操作不可撤销。',
    
    // 管理员面板
    'admin.dashboard': '管理员面板',
    'admin.title': '管理面板',
    'admin.totalSubscriptions': '总认购申请',
    'admin.pendingSubscriptions': '待审核申请',
    'admin.approvedSubscriptions': '已批准申请',
    'admin.totalTokenAmount': '总认购代币数',
    'admin.subscriptionManagement': '认购管理',
    'admin.refresh': '刷新数据',
    'admin.refreshing': '刷新中...',
    'admin.filterProject': '项目筛选',
    'admin.allProjects': '所有项目',
    'admin.filterStatus': '状态筛选',
    'admin.allStatuses': '所有状态',
    'admin.search': '搜索',
    'admin.searchPlaceholder': '搜索用户地址、项目代码、用户ID、项目名称...',
    'admin.loading': '加载中...',
    'admin.noSubscriptions': '暂无认购申请',
    'admin.id': 'ID',
    'admin.projectCode': '项目代码',
    'admin.projectName': '项目名称',
    'admin.userId': '用户ID',
    'admin.userAddress': '用户地址',
    'admin.tradeType': '交易类型',
    'admin.tokenAmount': '代币数量',
    'admin.annualYield': '年化收益率',
    'admin.expectedReturn': '预期收益',
    'admin.network': '网络',
    'admin.status': '状态',
    'admin.applicationTime': '申请时间',
    'admin.actions': '操作',
    'admin.tokens': '代币',
    'admin.na': 'N/A',
    'admin.startReview': '开始审批',
    'admin.approve': '通过',
    'admin.reject': '拒绝',
    'admin.verifyPayment': '核查支付',
    'admin.complete': '完成',
    'admin.details': '详情',
    'admin.previousPage': '上一页',
    'admin.nextPage': '下一页',
    'admin.page': '第',
    'admin.of': '页，共',
    'admin.pages': '页',
    'admin.statusApplied': '已申请',
    'admin.statusUnderReview': '审批中',
    'admin.statusApproved': '已通过',
    'admin.statusPaymentSubmitted': '已提交支付',
    'admin.statusPaymentConfirmed': '支付已确认',
    'admin.statusCompleted': '已完成',
    'admin.statusRejected': '已拒绝',
    'admin.statusCancelled': '已取消',
    'admin.tradeTypeSubscribe': '代币认购',
    'admin.tradeTypeRedeem': '赎回利息',
    'admin.rejectReason': '请输入拒绝原因：',
    'admin.statusUpdatedTo': '状态已更新为',
    'admin.statusUpdateFailed': '状态变更失败',
    'admin.paymentNotFound': '未找到交易哈希，无法核查',
    'admin.confirmPaymentVerification': '确认要核查交易',
    'admin.paymentConfirmed': '支付已确认',
    'admin.paymentVerificationFailed': '支付核查失败',
    'admin.subscriptionDetails': '认购详情',
    'admin.project': '项目',
    'admin.user': '用户',
    'admin.quantity': '数量',
    'admin.transactionHash': '交易哈希',
    'admin.notSubmitted': '未提交',
    'admin.notes': '备注',
    'admin.none': '无',
    
    // ToBeListed 页面
    'tobelisted.loanSize': '贷款规模',
    'tobelisted.estYield': '预计收益率(IRR)',
    'tobelisted.term': '期限',
    'tobelisted.subscribed': '已认购',
    'tobelisted.totalOffering': '总发行量',
    'tobelisted.subscriptionProgress': '已认购',
    'tobelisted.relatedPartyInfo': '相关方信息',
    'tobelisted.issuer': '发行主体',
    'tobelisted.collateral': '底层资产',
    'tobelisted.sponsor': '保荐人',
    'tobelisted.valuer': '评估机构',
    'tobelisted.lawyer': '律师',
    'tobelisted.trustee': '监管方',
    'tobelisted.viewOnEtherscan': '在Etherscan上查看',
    'tobelisted.tba': 'TBA'
  },
  en: {
    // Common
    'common.home': 'Home',
    'common.products': 'Products',
    'common.about': 'About Us',
    'common.contact': 'Contact Us',
    'common.settings': 'Settings',
    'common.profile': 'Profile',
    'common.login': 'Login',
    'common.signup': 'Sign Up',
    'common.logout': 'Logout',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.loading': 'Loading...',
    'common.loadingVideo': 'Loading video...',
    'common.loadingProducts': 'Loading product data...',
    'common.videoLoadError': 'Video loading failed',
    'common.loadFailed': 'Load failed',
    'common.retry': 'Retry',
    'common.refresh': 'Refresh',
    'common.close': 'Close',
    'common.sending': 'Sending...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.browserNotSupported': 'Your browser does not support video playback',
    'common.skipVideo': 'Skip Video',
    
    // Navigation
    'nav.home': 'Home',
    'nav.listedProjects': 'Tokenised RWA',
    'nav.toBeListed': 'To Be Tokenised RWA',
    'nav.trading': 'Trading',
    'nav.about': 'About Us',
    'nav.contact': 'Contact Us',
    'nav.more': 'More',
    'nav.portfolio': 'My Portfolio',
    'nav.settings': 'Settings',
    'nav.profile': 'Profile',
    'nav.notifications': 'Notifications',
    
    // Wallet
    'wallet.connect': 'Connect Wallet',
    'wallet.connect.description': 'Select a MetaMask account to connect to your profile:',
    'wallet.connect.new': 'Connect New Wallet',
    'wallet.connected': 'Connected',
    'wallet.disconnect': 'Disconnect Wallet',
    'wallet.disconnect.confirm': 'Are you sure you want to disconnect this wallet?',
    'wallet.disconnect.select': 'Select the wallet account you want to disconnect:',
    'wallet.disconnected': 'Wallet Disconnected',
    'wallet.management': 'Wallet Management',
    'wallet.networkSwitchNote': 'When you switch the network in your wallet, the network on this page will be automatically switched',
    'wallet.address': 'Wallet Address',
    'wallet.balance': 'Balance',
    'wallet.transaction': 'Transaction',
    'wallet.noAccounts': 'No other accounts found in MetaMask.',
    'wallet.addAccounts': 'Please add more accounts in MetaMask and try again.',
    'wallet.account': 'Account',
    'wallet.copy': 'Copy',
    'wallet.copied': 'Copied',
    'wallet.connectWalletManagement': 'Please connect your wallet in wallet management',
    'wallet.currentNetwork': 'Current Network',
    'wallet.portfolio': 'Portfolio',
    'wallet.insertContractAddress': 'Or you can insert your contract address here',
    'wallet.pasteERC20Address': 'Paste ERC20 contract address',
    'wallet.labelOptional': 'Label (optional)',
    'wallet.addToken': 'Add Token',
    'wallet.refresh': 'Refresh',
    'wallet.refreshTokens': 'Refresh Token List',
    'wallet.tokens': 'Tokens',
    'wallet.clickForDetails': 'Click for details',
    
    // Token Detail
    'tokenDetail.title': 'Token Details',
    'tokenDetail.overview': 'Overview',
    'tokenDetail.networkName': 'Network name',
    'tokenDetail.contractAddress': 'Contract address',
    'tokenDetail.tokenDecimal': 'Token decimal',
    'tokenDetail.spendingCaps': 'Spending caps',
    'tokenDetail.tokenImportDate': 'Token import date',
    'tokenDetail.tokenImportSource': 'Token import source',
    'tokenDetail.viewAssetInExplorer': 'View Asset in explorer',
    'tokenDetail.hide': 'Hide',
    'tokenDetail.deleteFromWallet': 'Delete from my wallet',
    'tokenDetail.hiddenSuccessfully': 'Hidden successfully',
    'tokenDetail.hideFailed': 'Hide failed',
    'tokenDetail.deletedFromCustomTokens': 'Deleted from custom tokens',
    'tokenDetail.deleteFailed': 'Delete failed',
    'wallet.connectSelectedAccount': 'Connect Selected Account',
    'wallet.loadingAccounts': 'Loading accounts...',
    'wallet.account': 'Account',
    'wallet.disconnectSuccess': 'Wallet Disconnected',
    'wallet.disconnectSuccessMsg': 'Wallet has been successfully disconnected',
    'wallet.addressAdded': 'Wallet address {address} has been added',
    'wallet.addressExists': 'This wallet address already exists',
    'wallet.invalidAddress': 'Please enter a valid Ethereum address',
    'wallet.noWalletToSet': 'No wallet address available to set',
    'wallet.primaryWalletSet': 'Primary wallet has been set to: {wallet}',
    'wallet.invalidSelection': 'Invalid selection',
    'wallet.walletDisconnected': 'Wallet {address} has been disconnected',
    
    // Settings
    'settings.title': 'Settings',
    'settings.subtitle': 'Manage your application settings',
    'settings.general': 'General',
    'settings.general.description': 'Basic application settings and preferences',
    'settings.theme': 'Theme',
    'settings.theme.description': 'Choose your preferred theme',
    'settings.language': 'Language',
    'settings.language.description': 'Choose your preferred language',
    'settings.theme.dark': 'Dark',
    'settings.theme.light': 'Light',
    'settings.language.zh': '中文',
    'settings.language.en': 'English',
    'settings.timezone': 'Timezone',
    'settings.timezone.description': 'Set your local timezone',
    'settings.timezone.utc': 'UTC',
    'settings.timezone.est': 'Eastern Time',
    'settings.timezone.pst': 'Pacific Time',
    'settings.timezone.cst': 'China Standard Time',
    'settings.notifications': 'Notifications',
    'settings.notifications.description': 'Notification preferences and alert settings',
    'settings.privacy': 'Privacy',
    'settings.privacy.description': 'Privacy controls and data settings',
    'settings.security': 'Security',
    'settings.security.description': 'Password, authentication and security settings',
    'settings.wallet': 'Wallet',
    'settings.wallet.description': 'Wallet connection and transaction settings',
    'settings.performance': 'Performance',
    'settings.performance.description': 'Performance optimization and cache settings',
    'settings.account': 'Account',
    'settings.account.description': 'Account options and profile settings',
    'settings.trading': 'Trading',
    'settings.trading.description': 'Trading preferences and option settings',
    'settings.advanced': 'Advanced',
    'settings.advanced.description': 'Advanced settings and developer options',
    
    // Intro Video
    'settings.introVideo': 'Intro Video',
    'settings.introVideo.description': 'Re-watch the website intro video',
    'settings.introVideo.watch': 'Watch Intro Video',
    
    // Security Settings
    'settings.password': 'Password',
    'settings.password.description': 'Change your account password',
    'settings.password.change': 'Change Password',
    'settings.sessionTimeout': 'Session Timeout',
    'settings.sessionTimeout.description': 'Set automatic logout time',
    'settings.sessionTimeout.15min': '15 minutes',
    'settings.sessionTimeout.30min': '30 minutes',
    'settings.sessionTimeout.1hour': '1 hour',
    'settings.sessionTimeout.8hours': '8 hours',
    'settings.loginAlerts': 'Login Alerts',
    'settings.loginAlerts.description': 'Receive notifications for new login attempts',
    
    // Wallet Settings
    'settings.defaultWallet': 'Default Wallet',
    'settings.defaultWallet.description': 'Choose your preferred wallet provider',
    'settings.defaultWallet.metamask': 'MetaMask',
    'settings.defaultWallet.walletconnect': 'WalletConnect',
    'settings.autoConnect': 'Auto Connect',
    'settings.autoConnect.description': 'Automatically connect wallet on page load',
    'settings.gasSettings': 'Gas Settings',
    'settings.gasSettings.description': 'Configure transaction gas preferences',
    'settings.gasSettings.configure': 'Gas Settings',
    'settings.connectWallet': 'Connect Wallet',
    'settings.connectWallet.description': 'Connect or disconnect your wallet',
    'settings.connectWallet.button': 'Connect Wallet',
    'settings.walletAddress': 'Wallet Address',
    'settings.walletAddress.description': 'View your wallet address',
    'settings.walletAddress.view': 'View Address',
    
    // Notification Settings
    'settings.pushNotifications': 'Push Notifications',
    'settings.pushNotifications.description': 'Enable browser push notifications',
    'settings.emailNotifications': 'Email Notifications',
    'settings.emailNotifications.description': 'Receive important updates via email',
    'settings.smsNotifications': 'SMS Notifications',
    'settings.smsNotifications.description': 'Receive important updates via SMS',
    
    // Performance Settings
    'settings.autoRefresh': 'Auto Refresh',
    'settings.autoRefresh.description': 'Automatically refresh data',
    'settings.autoRefresh.disabled': 'Disabled',
    'settings.autoRefresh.30sec': '30 seconds',
    'settings.autoRefresh.1min': '1 minute',
    'settings.autoRefresh.5min': '5 minutes',
    'settings.cacheSize': 'Cache Size',
    'settings.cacheSize.description': 'Maximum cache storage size',
    'settings.clearCache': 'Clear Cache',
    'settings.clearCache.description': 'Clear all cached data',
    'settings.clearCache.button': 'Clear Cache',
    
    // Account Settings
    'settings.profileVisibility': 'Profile Visibility',
    'settings.profileVisibility.description': 'Control who can see your personal information',
    'settings.profileVisibility.public': 'Public',
    'settings.profileVisibility.friends': 'Friends Only',
    'settings.profileVisibility.private': 'Private',
    'settings.twoFactorAuth': 'Two-Factor Authentication',
    'settings.twoFactorAuth.description': 'Add an extra layer of security to your account',
    'settings.twoFactorAuth.enable': 'Enable Two-Factor Auth',
    
    // Trading Settings
    'settings.defaultTradingPair': 'Default Trading Pair',
    'settings.defaultTradingPair.description': 'Set your preferred trading pair for quick access',
    'settings.defaultTradingPair.ethUsdt': 'ETH/USDT (Ethereum/USD)',
    'settings.defaultTradingPair.btcUsdt': 'BTC/USDT (Bitcoin/USD)',
    'settings.defaultTradingPair.usdcUsdt': 'USDC/USDT (USD Stablecoin/USD)',
    'settings.autoConfirmTrades': 'Auto Confirm Trades',
    'settings.autoConfirmTrades.description': 'Automatically confirm trades below specified amount',
    'settings.priceAlerts': 'Price Alerts',
    'settings.priceAlerts.description': 'Get notified when price reaches your target',
    'settings.priceAlerts.manage': 'Manage Alerts',
    
    // Privacy Settings
    'settings.dataCollection': 'Data Collection',
    'settings.dataCollection.description': 'Allow us to collect anonymous usage data',
    'settings.marketingEmails': 'Marketing Emails',
    'settings.marketingEmails.description': 'Receive promotional emails and updates',
    'settings.thirdPartySharing': 'Third-Party Sharing',
    'settings.thirdPartySharing.description': 'Allow sharing data with trusted partners',
    
    // Advanced Settings
    'settings.apiAccess': 'API Access',
    'settings.apiAccess.description': 'Manage your API keys and permissions',
    'settings.apiAccess.configure': 'API Settings',
    'settings.exportData': 'Export Data',
    'settings.exportData.description': 'Download your account data',
    'settings.exportData.button': 'Export',
    'settings.analytics': 'Analytics',
    'settings.analytics.description': 'Help improve the application by sharing usage data',
    'settings.resetPreferences': 'Reset Preferences',
    'settings.resetPreferences.description': 'Reset all options to default values',
    'settings.resetPreferences.button': 'Reset All',
    
    // Projects
    'project.title': 'Projects',
    'project.name': 'Project Name',
    'project.code': 'Project Code',
    'project.status': 'Status',
    'project.yield': 'Yield',
    'project.term': 'Term',
    'project.amount': 'Amount',
    'project.progress': 'Progress',
    'project.details': 'Details',
    'project.invest': 'Invest',
    'project.trade': 'Trade',
    'project.loanAmount': 'Loan Amount',
    'project.interestRate': 'Expected Yield',
    'project.perYear': ' p.a.',
    'project.loanTerm': 'Loan Term',
    'project.months': ' Months',
    'project.currentSubscription': 'Current Subscription',
    'project.totalOffering': 'Total Offering',
    'project.subscribed': 'Subscribed',
    'project.partyInfo': 'Party Information',
    'project.issuer': 'Issuer',
    'project.underlyingAsset': 'Underlying Asset',
    'project.sponsor': 'Sponsor',
    'project.valuer': 'Valuer',
    'project.lawyer': 'Lawyer',
    'project.trustee': 'Trustee',
    'project.viewOnEtherscan': 'View on Etherscan',
    
    // Profile
    'profile.title': 'Profile',
    'profile.info': 'Personal Information',
    'profile.email': 'Email',
    'profile.phone': 'Phone',
    'profile.wallet': 'Wallet',
    'profile.kyc': 'KYC Verification',
    'profile.whitelist': 'Whitelist',
    'profile.trading': 'Trading Permission',
    
    // About Us
    'about.title': 'About Us',
    'about.headline': 'We are RWA Dealmakers focused on packaging real estate assets into RWA underlying assets that investors love',
    'about.description': 'We are committed to providing investors with a transparent, secure, and efficient real estate tokenization investment platform.',
    'about.intro1': 'We are RWA Dealmakers specializing in packaging real estate assets into RWA underlying assets that investors favor. Our platform prioritizes the safety of RWA investors\' funds, carefully selecting legally compliant, low-risk, high-return quality assets (such as first-lien residential mortgage assets in Australia with loan-to-value ratios not exceeding 70% and interest rates of approximately 9%), facilitating transactions between investors and asset holders.',
    'about.intro2': 'The underlying assets displayed on our platform are protected by the laws of the countries where the assets are located, and funds can freely enter and exit these countries. If investors require it, the project transaction structure can enable independent segregation and custody of underlying assets and funds to qualified third-party institutions.',
    'about.intro3': 'In addition to facilitating transactions between investors and RWA underlying asset holders, our platform also integrates full-chain ecosystem cooperation for RWA tokenization, covering professional RWA tokenization technology service companies, licensed RWA token issuers and exchanges, ensuring that RWA tokenization is legal, efficient, and cost-effective for successful public or private issuance.',
    
    // Contact Us
    'contact.title': 'Contact Us',
    'contact.description': 'If you would like to use real estate assets or real estate mortgage loan assets as underlying assets for RWA financing, or if you are interested in purchasing RWA assets, please contact us.',
    'contact.name': 'Name',
    'contact.name.placeholder': 'Please enter your full name',
    'contact.email': 'Email',
    'contact.email.placeholder': 'Please enter your email address',
    'contact.type': 'Type',
    'contact.type.placeholder': 'Please select',
    'contact.type.individual': 'Individual',
    'contact.type.business': 'Business',
    'contact.type.other': 'Other',
    'contact.subject': 'Subject',
    'contact.subject.placeholder': 'Please select',
    'contact.subject.investor': 'Investment Inquiry',
    'contact.subject.asset_holder': 'Asset Listing',
    'contact.subject.general': 'General Question',
    'contact.subject.technical': 'Technical Support',
    'contact.subject.business': 'Business Partnership',
    'contact.subject.other': 'Other',
    'contact.message': 'Message',
    'contact.message.placeholder': 'Tell us what project you would like to invest in...',
    'contact.send': 'Send Message',
    'follow.us': 'Follow Us',
    
    // Footer
    'footer.disclaimer': 'Disclaimer: The information provided on this platform is for reference only and does not guarantee its authenticity, accuracy or completeness, nor does it constitute an investment invitation or investment advice.',
    'footer.copyright': '© 2025 RWA Dealmaker. All rights reserved.',
    
    // Trading Page - Project Information
    'trade.projectInfo': 'Project Information',
    'trade.issuer': 'Issuer',
    'trade.estimateReturn': 'Estimate Return',
    'trade.tokenizedAmount': 'Tokenized Amount',
    'trade.underlyingAsset': 'Underlying Asset',
    'trade.valuer': 'Valuer',
    'trade.lawyer': 'Lawyer',
    'trade.trustee': 'Trustee',
    'trade.year': 'p.a.',
    
    // Underlying Asset - Loan Information
    'trade.underlyingAssetLoanInfo': 'Underlying Asset - Loan Information',
    'trade.lender': 'Lender',
    'trade.borrower': 'Borrower',
    'trade.loanAmount': 'Loan Amount',
    'trade.collateral': 'Collateral',
    'trade.valuation': 'Valuation',
    'trade.lvr': 'LVR',
    'trade.mortgageTitle': 'Mortgage Title',
    'trade.firstMortgage': 'First Mortgage',
    'trade.interestRate': 'Interest Rate',
    'trade.loanTerm': 'Loan Term',
    'trade.months': 'Months',
    'trade.defaultInterestRate': 'Default Interest Rate',
    
    // Collateral Information
    'trade.collateralInfo': 'Collateral Information',
    'trade.assetAddress': 'Asset Address',
    'trade.siteArea': 'Site Area',
    'trade.floorArea': 'Gross Floor Area',
    'trade.propertyType': 'Property Type',
    'trade.squareMeters': 'm²',
    
    // Token Information
    'trade.tokenInfo': 'Token Information',
    'trade.underlyingAssetSize': 'Underlying Asset Size',
    'trade.totalTokenizedAmount': 'Total Tokenized Amount',
    'trade.subscribedAmount': 'Subscribed Amount',
    'trade.subscriptionPercentage': 'Subscription Percentage',
    
    // Trading Page - Contract Address
    'trade.contractAddress': 'Contract Address',
    'trade.contractAddressDescription': 'The following contract addresses will be used for this transaction:',
    'trade.principalTokenAddress': 'Principal Token Address',
    'trade.interestTokenAddress': 'Interest Token Address',
    'trade.kycRegistryAddress': 'KYC Registry Address',
    'trade.loanIssuerAddress': 'Loan Issuer Address',
    'trade.continueTransaction': 'Continue Transaction',
    'trade.transactionSuccess': 'Transaction Successful!',
    'trade.transactionCompleted': 'Your transaction has been completed!',
    'trade.transactionDetails': 'Transaction Details',
    'trade.type': 'Type',
    'trade.buy': 'Buy',
    'trade.sell': 'Sell',
    'trade.amount': 'Amount',
    'trade.blockchainInfo': 'Blockchain Info',
    'trade.hash': 'Hash',
    'trade.block': 'Block',
    'trade.contractAddresses': 'Contract Addresses',
    'trade.principalToken': 'Principal Token',
    'trade.interestToken': 'Interest Token',
    'trade.loadingProjectData': 'Loading project data...',
    'trade.pleaseWait': 'Please wait while we load the project information',
    'trade.loadingFailed': 'Loading Failed',
    'trade.retry': 'Retry',
    'trade.subscriptionInfo': 'Subscription Information',
    'trade.totalOffering': 'Total Offering',
    'trade.subscribed': 'Subscribed',
    'trade.subscriptionRatio': 'Subscription Ratio',
    'trade.loanInfo': 'Loan Information',
    'trade.loanAmount': 'Loan Amount',
    'trade.expectedYield': 'Expected Yield',
    'trade.term': 'Term',
    'trade.ltvRatio': 'LTV Ratio',
    'trade.defaultRate': 'Default Rate',
    'trade.lender': 'Lender',
    'trade.borrower': 'Borrower',
    'trade.collateralInfo': 'Collateral Information',
    'trade.appraisalValue': 'Appraisal Value',
    'trade.address': 'Address',
    'trade.mortgageType': 'Mortgage Type',
    'trade.sponsor': 'Sponsor',
    'trade.appraiser': 'Appraiser',
    'trade.lawyer': 'Lawyer',
    'trade.trustee': 'Trustee',
    'trade.smartContractAddresses': 'Smart Contract Addresses',
    'trade.interestTokenAddressLabel': 'Interest Token Address',
    'trade.subscribe': 'Subscribe Now',
    'trade.walletAddress': 'Wallet Address',
    'trade.quantityTokens': 'Quantity (Tokens)',
    'trade.enterQuantity': 'Enter quantity',
    'trade.projectUpdates': 'Project Updates',
    'trade.newsItem1': 'Project officially launched, now accepting investment applications',
    'trade.newsItem2': 'Project due diligence completed, risk assessment report released',
    'trade.newsItem3': 'Collateral appraisal completed, valuation confirmed',
    'trade.newsItem4': 'Project listed, detailed information updated',
    
    // Subscription Summary
    'trade.subscriptionSummary': 'Subscription Summary',
    'trade.redemptionSummary': 'Redemption Summary',
    'trade.projectCode': 'Project Code',
    'trade.projectName': 'Project Name',
    'trade.tradeType': 'Trade Type',
    'trade.tokenPurchase': 'Token Purchase',
    'trade.interestRedemption': 'Interest Redemption',
    'trade.tokenAmount': 'Token Amount',
    'trade.tokens': 'Tokens',
    'trade.annualYield': 'Annual Yield',
    'trade.expectedReturn': 'Expected Return',
    'trade.loanTerm': 'Loan Term',
    'trade.riskWarning': 'Investment involves risks. Please read the project details carefully and assess your risk tolerance.',
    
    // Subscription Status Modal
    'trade.submitting': 'Submitting Subscription...',
    'trade.submittingDesc': 'Please wait while we process your subscription request',
    'trade.submitted': 'Subscription Submitted!',
    'trade.submittedDesc': 'Your subscription request has been successfully submitted, please wait for approval',
    'trade.failed': 'Subscription Failed',
    'trade.viewPortfolio': 'View Portfolio',
    'trade.resubmit': 'Resubmit',
    'trade.confirmSubscription': 'Confirm Subscription',
    'trade.confirmRedemption': 'Confirm Redemption',
    'trade.subscriptionSubmitted': 'Your subscription application has been submitted',
    'trade.checkEmailForUpdates': 'Please check your email for the link to track your application status',
    'trade.processing': 'Processing...',
    'trade.processingTitle': 'Processing...',
    'trade.processingDesc': 'We are processing your transaction request, please wait...',
    
    // Profile page
    'profile.personalCenter': 'Personal Center',
    'profile.personalInfo': 'Personal Information',
    'profile.email': 'Email:',
    'profile.phone': 'Phone:',
    'profile.password': 'Password:',
    'profile.verifyEmail': 'Verify Email',
    'profile.verifyPhone': 'Verify Phone',
    'profile.addPhone': 'Add Phone',
    'profile.changePhone': 'Change Phone',
    'profile.changePassword': 'Change Password',
    'profile.status': 'Status:',
    'profile.loadingUserInfo': 'Loading user information...',
    'profile.notProvided': 'Not provided',
    'profile.accountStatus': 'Account Status',
    'profile.kycVerification': 'KYC Verification',
    'profile.startVerification': 'Start Verification',
    'profile.tradingPermission': 'Trading Permission',
    'profile.start': 'Start',
    'profile.cancelVerification': 'Cancel Verification',
    'profile.logout': 'Logout',
    'profile.checkEmail': 'Check Your Email',
    'profile.verifyEmailDescription': 'We sent an email with a verification button to your email address.<br>Did you receive the email? If not, please check your spam folder or request a new verification email, valid for 3 days.<br>If you do not verify your email address within 3 days, you will need to create a new account.<br>If you encounter problems, please refer to account help.',
    'profile.accountHelp': 'Account Help',
    'profile.subscribe': 'Subscribe',
    'profile.unsubscribe': 'Unsubscribe',
    'profile.privacy': 'Privacy / Do Not Sell My Info',
    'profile.cookiePreferences': 'Cookie Preferences',
    'profile.confirm': 'Confirm',
    
    // Login page
    'login.title': 'Login to Your Account',
    'login.subtitle': 'Welcome to RWADealmaker',
    'login.email': 'Email',
    'login.emailPlaceholder': 'Enter your email',
    'login.password': 'Password',
    'login.passwordPlaceholder': 'Enter your password',
    'login.remember': 'Remember for 30 days',
    'login.forgotPassword': 'Forgot Password',
    'login.loginButton': 'Login',
    'login.loggingIn': 'Logging in...',
    'login.noAccount': "Don't have an account?",
    'login.signupLink': 'Sign Up',
    
    // Signup page
    'signup.title': 'Create Your Account',
    'signup.subtitle': 'Welcome to RWADealmaker',
    'signup.email': 'Email',
    'signup.emailPlaceholder': 'Enter your email',
    'signup.password': 'Password',
    'signup.passwordPlaceholder': 'Enter your password',
    'signup.confirmPassword': 'Confirm Password',
    'signup.confirmPasswordPlaceholder': 'Confirm your password',
    'signup.passwordMatch': '✓ Passwords match',
    'signup.passwordMismatch': '✗ Passwords do not match',
    'signup.name': 'Name',
    'signup.namePlaceholder': 'Enter your name',
    'signup.phone': 'Phone Number',
    'signup.phonePlaceholder': 'Enter your phone number',
    'signup.agreeTerms': 'I agree to',
    'signup.terms': 'Terms',
    'signup.and': 'and',
    'signup.privacyPolicy': 'Privacy Policy.',
    'signup.agreeEmailUpdates': 'I want to receive email updates from RWA.',
    'signup.signupButton': 'Sign Up',
    'signup.signingUp': 'Signing up...',
    'signup.haveAccount': 'Already have an account?',
    'signup.loginLink': 'Login',
    
    // KYC Verification page
    'kyc.back': 'Back',
    'kyc.title': 'KYC Verification',
    'kyc.cancelVerification': 'Cancel Verification',
    'kyc.step1': '1. Upload ID & auto-read',
    'kyc.step2': '2. Liveness',
    'kyc.step3': '3. Complete',
    'kyc.uploadIdTitle': 'Upload your ID and auto-read info',
    'kyc.uploadFront': 'Upload front image*',
    'kyc.uploadBack': 'Upload back image',
    'kyc.issuingCountry': 'Issuing country*',
    'kyc.selectCountry': 'Select…',
    'kyc.idType': 'ID type*',
    'kyc.selectIdType': 'Select…',
    'kyc.passport': 'Passport',
    'kyc.driverLicense': "Driver's license",
    'kyc.idCard': 'ID card',
    'kyc.residencePermit': 'Residence permit',
    'kyc.autoRead': 'Auto-read from ID',
    'kyc.autoReadHint': 'Will use OCR/parsing service to read first name, last name, DOB, etc.',
    'kyc.firstName': 'First name*',
    'kyc.lastName': 'Last name*',
    'kyc.dateOfBirth': 'Date of birth*',
    'kyc.idNumber': 'ID number',
    'kyc.cancel': 'Cancel',
    'kyc.continue': 'Continue',
    'kyc.livenessTitle': 'Liveness detection',
    'kyc.livenessDescription': 'Center your face in the frame and follow the instruction.',
    'kyc.enableCamera': 'Enable Camera',
    'kyc.livenessHint': 'When integrating Sumsub/Persona/Onfido, replace this area with their component and call complete() in the success callback.',
    'kyc.back': 'Back',
    'kyc.cancelLiveness': 'Cancel',
    'kyc.verifiedTitle': 'Your profile has been verified',
    'kyc.verifiedDescription': 'Please wait for the whitelist application...',
    'kyc.backToProfile': 'Back to Profile',
    'kyc.congratulations': 'Congratulations!',
    'kyc.kycCompleted': 'Your KYC verification has been completed successfully.',
    'kyc.eligibleForWhitelist': 'Now you are eligible to apply for the whitelist and start trading!',
    'kyc.maybeLater': 'Maybe Later',
    'kyc.applyForWhitelist': 'Apply for Whitelist',
    'kyc.applyingWhitelist': 'Applying for Whitelist...',
    'kyc.applyingWhitelistDescription': 'Please wait while we process your whitelist application.',
    'kyc.welcomeToWhitelist': 'Welcome to the Whitelist!',
    'kyc.whitelistSuccess': 'You have successfully joined the whitelist.',
    'kyc.canSubscribe': 'Now you can go to the Projects page to subscribe to your preferred assets!',
    'kyc.goToProjects': 'Go to Projects',
    'kyc.cancelKycTitle': 'Cancel KYC Verification',
    'kyc.cancelKycWarning': 'Canceling KYC will revoke your subscription eligibility.',
    'kyc.cancelKycConfirm': 'Are you sure you want to cancel KYC verification?',
    'kyc.continueKyc': 'Continue KYC',
    'kyc.yesCancelKyc': 'Yes, Cancel KYC',
    
    // Whitelist Application
    'whitelist.status': 'Whitelist Status',
    'whitelist.approved': 'Whitelist Approved',
    'whitelist.pending': 'Whitelist Application Pending',
    'whitelist.rejected': 'Not Eligible for Trading',
    'whitelist.apply': 'Apply for Whitelist',
    'whitelist.applyNow': 'Apply Now',
    'whitelist.checkStatus': 'Check Status',
    'whitelist.startTrading': 'Start Trading',
    'whitelist.reapply': 'Reapply',
    'whitelist.applicationTitle': 'Apply for Whitelist',
    'whitelist.applicationDescription': 'You are about to apply for the whitelist to start trading assets.',
    'whitelist.requirements': 'Requirements:',
    'whitelist.kycCompleted': 'KYC verification completed ✅',
    'whitelist.validWallet': 'Valid wallet connection',
    'whitelist.agreeTerms': 'Agree to terms and conditions',
    'whitelist.applying': 'Applying...',
    'whitelist.close': 'Close',
    'whitelist.confirm': 'Confirm',
    
    // Notifications page
    'notifications.title': 'Notifications',
    'notifications.all': 'All',
    'notifications.unread': 'Unread',
    'notifications.read': 'Read',
    'notifications.markAllRead': 'Mark all as read',
    'notifications.markAsRead': 'Mark as read',
    'notifications.refresh': 'Refresh',
    'notifications.loading': 'Loading...',
    'notifications.noNotifications': 'No notifications',
    'notifications.noNotificationsDesc': 'You have not received any notifications yet',
    'notifications.viewDetails': 'View Details',
    'notifications.delete': 'Delete',
    'notifications.previous': 'Previous',
    'notifications.next': 'Next',
    'notifications.page': 'Page',
    'notifications.justNow': 'Just now',
    'notifications.minutesAgo': '{count} minutes ago',
    'notifications.hoursAgo': '{count} hours ago',
    'notifications.daysAgo': '{count} days ago',
    
    // Notification types
    'notifications.types.transactionSuccess': 'Transaction Successfully Completed',
    'notifications.types.newProjectLaunched': 'New Project Launched',
    'notifications.types.subscriptionProgress': 'Subscription Progress Update',
    'notifications.types.kycStatusUpdate': 'KYC Status Update',
    'notifications.types.whitelistStatusUpdate': 'Whitelist Status Update',
    'notifications.types.principalTokenReceived': 'Principal Token Received',
    'notifications.types.interestTokenReceived': 'Interest Token Received',
    'notifications.types.projectMaturity': 'Project Maturity Reminder',
    'notifications.types.subscriptionApplied': 'Subscription Applied',
    'notifications.types.subscriptionUnderReview': 'Subscription Under Review',
    'notifications.types.subscriptionApproved': 'Subscription Approved',
    
    // Notification action buttons
    'notifications.actions.viewPortfolio': 'View Portfolio',
    'notifications.actions.viewProject': 'View Project',
    'notifications.actions.viewProfile': 'View Profile',
    'notifications.actions.viewDetails': 'View Details',
    'notifications.actions.payNow': 'Pay Now',
    'notifications.clearAll': 'Clear All Notifications',
    'notifications.clearAllConfirm': 'Are you sure you want to delete all notifications? This action cannot be undone.',
    
    // Admin Dashboard
    'admin.dashboard': 'Admin Dashboard',
    'admin.title': 'Admin Panel',
    'admin.totalSubscriptions': 'Total Subscriptions',
    'admin.pendingSubscriptions': 'Pending Subscriptions',
    'admin.approvedSubscriptions': 'Approved Subscriptions',
    'admin.totalTokenAmount': 'Total Token Amount',
    'admin.subscriptionManagement': 'Subscription Management',
    'admin.refresh': 'Refresh Data',
    'admin.refreshing': 'Refreshing...',
    'admin.filterProject': 'Filter by Project',
    'admin.allProjects': 'All Projects',
    'admin.filterStatus': 'Filter by Status',
    'admin.allStatuses': 'All Statuses',
    'admin.search': 'Search',
    'admin.searchPlaceholder': 'Search user address, project code, user ID, project name...',
    'admin.loading': 'Loading...',
    'admin.noSubscriptions': 'No subscription applications',
    'admin.id': 'ID',
    'admin.projectCode': 'Project Code',
    'admin.projectName': 'Project Name',
    'admin.userId': 'User ID',
    'admin.userAddress': 'User Address',
    'admin.tradeType': 'Trade Type',
    'admin.tokenAmount': 'Token Amount',
    'admin.annualYield': 'Annual Yield',
    'admin.expectedReturn': 'Expected Return',
    'admin.network': 'Network',
    'admin.status': 'Status',
    'admin.applicationTime': 'Application Time',
    'admin.actions': 'Actions',
    'admin.tokens': 'Tokens',
    'admin.na': 'N/A',
    'admin.startReview': 'Start Review',
    'admin.approve': 'Approve',
    'admin.reject': 'Reject',
    'admin.verifyPayment': 'Verify Payment',
    'admin.complete': 'Complete',
    'admin.details': 'Details',
    'admin.previousPage': 'Previous',
    'admin.nextPage': 'Next',
    'admin.page': 'Page',
    'admin.of': ' of ',
    'admin.pages': '',
    'admin.statusApplied': 'Applied',
    'admin.statusUnderReview': 'Under Review',
    'admin.statusApproved': 'Approved',
    'admin.statusPaymentSubmitted': 'Payment Submitted',
    'admin.statusPaymentConfirmed': 'Payment Confirmed',
    'admin.statusCompleted': 'Completed',
    'admin.statusRejected': 'Rejected',
    'admin.statusCancelled': 'Cancelled',
    'admin.tradeTypeSubscribe': 'Token Subscribe',
    'admin.tradeTypeRedeem': 'Redeem Interest',
    'admin.rejectReason': 'Please enter rejection reason:',
    'admin.statusUpdatedTo': 'Status updated to',
    'admin.statusUpdateFailed': 'Status update failed',
    'admin.paymentNotFound': 'Transaction hash not found, unable to verify',
    'admin.confirmPaymentVerification': 'Confirm to verify transaction',
    'admin.paymentConfirmed': 'Payment confirmed',
    'admin.paymentVerificationFailed': 'Payment verification failed',
    'admin.subscriptionDetails': 'Subscription Details',
    'admin.project': 'Project',
    'admin.user': 'User',
    'admin.quantity': 'Quantity',
    'admin.transactionHash': 'Transaction Hash',
    'admin.notSubmitted': 'Not submitted',
    'admin.notes': 'Notes',
    'admin.none': 'None',
    
    // ToBeListed page
    'tobelisted.loanSize': 'LOAN SIZE',
    'tobelisted.estYield': 'EST. YIELD (IRR)',
    'tobelisted.term': 'TERM',
    'tobelisted.subscribed': 'Subscribed',
    'tobelisted.totalOffering': 'Total Offering',
    'tobelisted.subscriptionProgress': 'Subscribed',
    'tobelisted.relatedPartyInfo': 'Related Party Info',
    'tobelisted.issuer': 'Issuer',
    'tobelisted.collateral': 'Collateral',
    'tobelisted.sponsor': 'Sponsor',
    'tobelisted.valuer': 'Valuer',
    'tobelisted.lawyer': 'Lawyer',
    'tobelisted.trustee': 'Trustee',
    'tobelisted.viewOnEtherscan': 'View on Etherscan',
    'tobelisted.tba': 'TBA'
  }
}

// 应用语言到文档
const applyLanguage = (languageCode) => {
  const language = languages[languageCode]
  if (!language) return

  const root = document.documentElement
  root.setAttribute('lang', languageCode)
  root.setAttribute('dir', language.dir)
  localStorage.setItem('rwa-language', languageCode)
  currentLanguage.value = languageCode
}

// 从 localStorage 加载保存的语言
const loadSavedLanguage = () => {
  const saved = localStorage.getItem('rwa-language')
  if (saved && languages[saved]) {
    currentLanguage.value = saved
  } else {
    // 如果没有保存的语言，使用浏览器语言偏好
    const browserLang = navigator.language.split('-')[0]
    currentLanguage.value = languages[browserLang] ? browserLang : 'zh'
  }
  applyLanguage(currentLanguage.value)
}

// 切换语言
const setLanguage = (languageCode) => {
  if (!languages[languageCode]) {
    console.warn(`Language "${languageCode}" not found`)
    return
  }
  
  currentLanguage.value = languageCode
  applyLanguage(languageCode)
}

// 获取翻译文本
const t = (key) => {
  const currentTranslations = translations[currentLanguage.value]
  if (!currentTranslations) {
    console.warn(`Translations not found for language: ${currentLanguage.value}`)
    return key
  }
  
  return currentTranslations[key] || key
}

// 获取当前语言信息
const getCurrentLanguage = computed(() => {
  return {
    name: languages[currentLanguage.value].name,
    code: currentLanguage.value
  }
})

// 获取所有可用语言
const getAvailableLanguages = () => {
  return Object.entries(languages).map(([value, config]) => ({
    value,
    name: config.name
  }))
}

// 初始化语言
const initLanguage = () => {
  loadSavedLanguage()
}

export function useLanguage() {
  return {
    currentLanguage,
    setLanguage,
    getCurrentLanguage,
    getAvailableLanguages,
    initLanguage,
    applyLanguage,
    t
  }
}
